package e_bill_receipt;

import static e_bill_receipt.form.discount_tf;
import static e_bill_receipt.form.id_tf1;
import static e_bill_receipt.form.netbill_tf;
import static e_bill_receipt.form.num_of_items_tf;
import static e_bill_receipt.form.total_bill_tf;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.util.logging.Level;
import java.util.logging.Logger;
import static e_bill_receipt.form.netbill_tf;

/**
 *
 * @author Rashda Khanzada
 */
public class receipt extends javax.swing.JFrame {

    /**
     * Creates new form receipt
     */
    public receipt() {
        initComponents();
        id_lb.setText(id_tf1.getText());
        num_of_items_lb.setText(num_of_items_tf.getText());
        totalbill_lb.setText(total_bill_tf.getText());
        discount_lb.setText(discount_tf.getText());
        netbill_lb.setText(netbill_tf.getText());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        netbill_lb = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        id_lb = new javax.swing.JLabel();
        num_of_items_lb = new javax.swing.JLabel();
        totalbill_lb = new javax.swing.JLabel();
        discount_lb = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        netbill_lb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(netbill_lb);
        netbill_lb.setBounds(260, 300, 120, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("id");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 100, 100, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("number of items");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 150, 150, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("total bill");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 200, 150, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("discount");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(70, 250, 150, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("net bill");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(70, 300, 150, 40);

        id_lb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(id_lb);
        id_lb.setBounds(260, 100, 120, 30);

        num_of_items_lb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(num_of_items_lb);
        num_of_items_lb.setBounds(260, 150, 120, 40);

        totalbill_lb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(totalbill_lb);
        totalbill_lb.setBounds(260, 200, 120, 40);

        discount_lb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(discount_lb);
        discount_lb.setBounds(260, 250, 120, 40);

        jLabel1.setText("*******************************************************************************");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 70, 400, 20);

        jLabel7.setText("*******************************************************************************");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 20, 400, 20);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("E-BILL RECEIPT");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(130, 40, 230, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 350);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 360, 110, 30);

        setSize(new java.awt.Dimension(440, 454));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          PrinterJob job=PrinterJob.getPrinterJob();
        job.setJobName("Print Data");
        job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf,int PageNum){
                if(PageNum>0)
                return Printable.NO_SUCH_PAGE;
                Graphics2D g2=(Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(1.6, 1.6);
                jPanel1.paint(g2);
                return Printable.PAGE_EXISTS;
            }
        });
        boolean ok=job.printDialog();
        if(ok){
            try{
                job.print();
            } catch (PrinterException ex) {
                Logger.getLogger(receipt.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel discount_lb;
    private javax.swing.JLabel id_lb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel netbill_lb;
    private javax.swing.JLabel num_of_items_lb;
    private javax.swing.JLabel totalbill_lb;
    // End of variables declaration//GEN-END:variables
}
