package currencyconverter;
/**
 *
 * @author Rashda Khanzada
 */
import javax.swing.JOptionPane;
public class converter extends javax.swing.JFrame {

    /**
     * Creates new form converter
     */
    public converter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf1 = new javax.swing.JTextField();
        to = new javax.swing.JLabel();
        from = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        fromcombo = new javax.swing.JComboBox<>();
        tocombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Currency Converter");
        setResizable(false);
        getContentPane().setLayout(null);

        tf1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(tf1);
        tf1.setBounds(160, 90, 170, 40);

        to.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        to.setText("TO");
        getContentPane().add(to);
        to.setBounds(60, 170, 80, 40);

        from.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        from.setText("FROM");
        getContentPane().add(from);
        from.setBounds(50, 90, 80, 40);

        tf2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(tf2);
        tf2.setBounds(160, 170, 170, 40);

        fromcombo.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(fromcombo);
        fromcombo.setBounds(390, 90, 210, 40);

        tocombo.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        tocombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tocomboActionPerformed(evt);
            }
        });
        getContentPane().add(tocombo);
        tocombo.setBounds(390, 170, 210, 39);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bitcoin-Exchange-Rate-696x449.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 660, 300);

        setSize(new java.awt.Dimension(668, 335));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
   //Store the currency in combobox 1
    public void combo1(){
    String arr[]={"Argentine Peso","Bajan Dollar","Chinese Yuan","Danish Krone","Euro","Fijian Dollar","Japanese Yen","Pakistani Rupees"};
        for(int i=0;i<arr.length;i++){
         fromcombo.addItem(arr[i]);
        
         }
    }
    
    //Store the currency in combobox 2
    public void combo2(){
    String arr2[]={"Algerian Dinar","Bajan Dollar","Canadian Dollar","Egyptian Pounds","Pakistani Rupees","Serbian Dinar"};
        for(int i=0;i<arr2.length;i++){
        tocombo.addItem(arr2[i]);
        }
    }
 
    //currency conversion
    private void tocomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tocomboActionPerformed
      
        try{  
        Object from_combo=fromcombo.getSelectedItem();
        Object to_combo=tocombo.getSelectedItem();
        Double currency=Double.parseDouble(tf1.getText());
        
        //currency conversion of Argentine Peso 
        if(from_combo.equals("Argentine Peso")){
           if(to_combo.equals("Pakistani Rupees")){
              currency*=3.14;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Egyptian Pounds")){
              currency*=0.38;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Canadian Dollar")){
              currency*=0.030;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Serbian Dinar")){
              currency*=2.34;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Algerian Dinar")){
              currency*=2.65;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Bajan Dollar")){
              currency*=0.044;
              tf2.setText(String.valueOf(currency));
           }
        }
        
        //currency conversion of Bajan Dollar
        if(from_combo.equals("Bajan Dollar")){
           if(to_combo.equals("Pakistani Rupees")){
              currency*=71.04;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Egyptian Pounds")){
              currency*=0.38;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Canadian Dollar")){
              currency*=0.030;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Serbian Dinar")){
              currency*=2.34;
              tf2.setText(String.valueOf(currency));
           }
            else if(to_combo.equals("Algerian Dinar")){
              currency*=60.04;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Bajan Dollar")){
              JOptionPane.showMessageDialog(null,"same currency");
              tf2.setText("");
           }
        }
        
        //currency conversion of Chinese Yuan    
        if(from_combo.equals("Chinese Yuan")){
           if(to_combo.equals("Pakistani Rupees")){
              currency*=20.87;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Egyptian Pounds")){
              currency*=2.53;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Canadian Dollar")){
              currency*=0.20;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Serbian Dinar")){
              currency*=15.55;
              tf2.setText(String.valueOf(currency));
           }
            else if(to_combo.equals("Algerian Dinar")){
              currency*=17.62;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Bajan Dollar")){
              currency*=0.29;
              tf2.setText(String.valueOf(currency));
           }
        }
        
        //currency conversion of Danish Krone 
        if(from_combo.equals("Danish Krone")){
           if(to_combo.equals("Pakistani Rupees")){
              currency*=1.34;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Egyptian Pounds")){
              currency*=2.57;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Canadian Dollar")){
              currency*=0.20;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Serbian Dinar")){
              currency*=15.81;
              tf2.setText(String.valueOf(currency));
           }
            else if(to_combo.equals("Algerian Dinar")){
              currency*=17.91;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Bajan Dollar")){
              currency*=0.30;
              tf2.setText(String.valueOf(currency));
           }
        }
        
         //currency conversion of Euro 
        if(from_combo.equals("Euro")){
           if(to_combo.equals("Pakistani Rupees")){
              currency*=158.39;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Egyptian Pounds")){
              currency*=19.19;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Canadian Dollar")){
              currency*=1.51;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Serbian Dinar")){
              currency*=117.94;
              tf2.setText(String.valueOf(currency));
           }
            else if(to_combo.equals("Algerian Dinar")){
              currency*=133.72;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Bajan Dollar")){
              currency*=2.23;
              tf2.setText(String.valueOf(currency));
           }
        }
        
        //currency conversion of  Fijian Dollar
        if(from_combo.equals("Fijian Dollar")){
           if(to_combo.equals("Pakistani Rupees")){
              currency*=65.44;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Egyptian Pounds")){
              currency*=7.93;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Canadian Dollar")){
              currency*=0.62;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Serbian Dinar")){
              currency*=48.85;
              tf2.setText(String.valueOf(currency));
           }
            else if(to_combo.equals("Algerian Dinar")){
              currency*=55.39;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Bajan Dollar")){
              currency*=0.92;
              tf2.setText(String.valueOf(currency));
           }
        }
        
        
        //currency conversion of  Japanese Yen
        if(from_combo.equals("Japanese Yen")){
           if(to_combo.equals("Pakistani Rupees")){
              currency*=1.29;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Egyptian Pounds")){
              currency*=0.16;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Canadian Dollar")){
              currency*=0.012;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Serbian Dinar")){
              currency*=1.09;
              tf2.setText(String.valueOf(currency));
           }
            else if(to_combo.equals("Algerian Dinar")){
              currency*=55.39;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Bajan Dollar")){
              currency*=0.018;
              tf2.setText(String.valueOf(currency));
           }
        }
        
        //currency conversion of  Pakistani Rupees
        if(from_combo.equals("Pakistani Rupees")){
            if(to_combo.equals("Pakistani Rupees")){
              JOptionPane.showMessageDialog(null, "same currency");
              tf2.setText("");
           }
            if(to_combo.equals("Egyptian Pounds")){
              currency*=0.12;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Canadian Dollar")){
              currency*=0.0095;
              tf2.setText(String.valueOf(currency));
           }
           else if(to_combo.equals("Serbian Dinar")){
              currency*=0.75;
              tf2.setText(String.valueOf(currency));
           }
            else if(to_combo.equals("Algerian Dinar")){
              currency*=0.85;
              tf2.setText(String.valueOf(currency));
           }
            else if(to_combo.equals("Bajan Dollar")){
              currency=currency/71.04;
              tf2.setText(String.valueOf(currency));
           }
        }
      }
      catch(Exception e){}
    }//GEN-LAST:event_tocomboActionPerformed
     
    
  
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(converter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               converter c= new converter();
               c.setVisible(true);
               c.combo1();
               c.combo2();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel from;
    private javax.swing.JComboBox<String> fromcombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JLabel to;
    private javax.swing.JComboBox<String> tocombo;
    // End of variables declaration//GEN-END:variables
}
