package mobileinventory;


/**
 *
 * @author Rashda Khanzada
 */
public class Brandsframe extends javax.swing.JFrame {

    /**
     * Creates new form Brandsframe
     */
    public Brandsframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HTC = new javax.swing.JButton();
        qmobile = new javax.swing.JButton();
        samsung = new javax.swing.JButton();
        nokia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Brands");
        setResizable(false);
        getContentPane().setLayout(null);

        HTC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images1.jpg"))); // NOI18N
        HTC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HTCActionPerformed(evt);
            }
        });
        getContentPane().add(HTC);
        HTC.setBounds(250, 140, 220, 80);

        qmobile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.jpg"))); // NOI18N
        qmobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qmobileActionPerformed(evt);
            }
        });
        getContentPane().add(qmobile);
        qmobile.setBounds(250, 360, 220, 80);

        samsung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Samsung-670x3882.jpg"))); // NOI18N
        samsung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                samsungActionPerformed(evt);
            }
        });
        getContentPane().add(samsung);
        samsung.setBounds(250, 40, 220, 80);

        nokia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nokia_white_logo.png"))); // NOI18N
        nokia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nokiaActionPerformed(evt);
            }
        });
        getContentPane().add(nokia);
        nokia.setBounds(250, 250, 220, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jbareham_180424_2499_0007.01.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 730, 460);

        setSize(new java.awt.Dimension(742, 505));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void qmobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qmobileActionPerformed
       QMobile q = new QMobile();
       q.show();
    }//GEN-LAST:event_qmobileActionPerformed

    private void samsungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_samsungActionPerformed
        Samsung sam = new Samsung();
        sam.show();
    }//GEN-LAST:event_samsungActionPerformed

    private void HTCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HTCActionPerformed
        HTC h = new HTC();
        h.show();
    }//GEN-LAST:event_HTCActionPerformed

    private void nokiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nokiaActionPerformed
       Nokia n = new Nokia();
        n.show();
    }//GEN-LAST:event_nokiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Brandsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Brandsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Brandsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Brandsframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Brandsframe brand=new Brandsframe();
                brand.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HTC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton nokia;
    private javax.swing.JButton qmobile;
    private javax.swing.JButton samsung;
    // End of variables declaration//GEN-END:variables
}
