/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timer_in_java;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;



/**
 *
 * @author Rashda Khanzada
 */
public class Timer_frame extends javax.swing.JFrame {

    /**
     * Creates new form Timer
     */
    Timer t;
    public Timer_frame() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timer_lb = new javax.swing.JLabel();
        stop_button = new javax.swing.JButton();
        start_button = new javax.swing.JButton();
        reset_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"Timer\"");
        setResizable(false);
        getContentPane().setLayout(null);

        timer_lb.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        timer_lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(timer_lb);
        timer_lb.setBounds(110, 90, 370, 140);

        stop_button.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        stop_button.setText("STOP");
        stop_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stop_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(stop_button);
        stop_button.setBounds(220, 270, 120, 40);

        start_button.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        start_button.setText("START");
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(start_button);
        start_button.setBounds(70, 270, 120, 40);

        reset_button.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        reset_button.setText("RESET");
        reset_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reset_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(reset_button);
        reset_button.setBounds(370, 270, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/6cd9f7af3b860dd651c72057f349814d.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 410);

        setSize(new java.awt.Dimension(602, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 int counter=0;
    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
        t=new Timer(1000,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
              timer_lb.setText(String.valueOf(counter));
              counter++;
            }    
        });
        t.start();
        
    }//GEN-LAST:event_start_buttonActionPerformed

    private void stop_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stop_buttonActionPerformed
       t.stop();   
    }//GEN-LAST:event_stop_buttonActionPerformed
int l;
    private void reset_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reset_buttonActionPerformed
         t.stop();
         l=0;
         t=new Timer(1000,new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent ae) {
              timer_lb.setText(String.valueOf(l));
              l++;
            }    
        });
        t.start();
    }//GEN-LAST:event_reset_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Timer_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reset_button;
    private javax.swing.JButton start_button;
    private javax.swing.JButton stop_button;
    private javax.swing.JLabel timer_lb;
    // End of variables declaration//GEN-END:variables
}
