package compshop;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
public class InventoryItems extends javax.swing.JFrame {
    public InventoryItems() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inventory Items Record");
        setResizable(false);
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.Keyboard", "2.Mouse", "3.Monitors", "4.VGA cables", "5.Graphic cards", "6.LCD", "7.Laptops" }));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(190, 30, 150, 30);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(120, 100, 310, 130);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 320);

        setSize(new java.awt.Dimension(566, 363));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        int obj=evt.getKeyCode();
        if(obj==KeyEvent.VK_1){
           jTextArea1.setText("Total keyboards in inventory: 15\n" +"Supplier name: Mr. Amin\n" +"Price per Item :  Rs. 150");
      }
        else if(obj==KeyEvent.VK_2){
           jTextArea1.setText("Total mouse in inventory: 20\n" +"Supplier name: Mr. Amin\n" +"Price per Item :  Rs. 120");
        }
        else if(obj==KeyEvent.VK_3){
           jTextArea1.setText("Total monitors in inventory: 15\n" +"Supplier name: Mr. Amin\n" +"Price per Item :  Rs. 2000");
        }
        else if(obj==KeyEvent.VK_4){
           jTextArea1.setText("Total VGA cables in inventory: 30\n" +"Supplier name: Mr. Amin\n" +"Price per Item :  Rs. 120");
        }
        else if(obj==KeyEvent.VK_5){
           jTextArea1.setText("Total graphic cards in inventory: 20\n" +"Supplier name: Mr. Amin\n" +"Price per Item :  Rs. 400");
        }
        else if(obj==KeyEvent.VK_6){
           jTextArea1.setText("Total LCD in inventory: 30\n" +"Supplier name: Mr. Amin\n" +"Price per Item :  Rs. 3000");
        }
        else if(obj==KeyEvent.VK_7){
           jTextArea1.setText("Total laptops in inventory: 30\n" +"Supplier name: Mr. Amin\n" +"Price per Item :  Rs. 35000");
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryItems().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
