/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digital_library;

import static digital_library.Search_book.available_copies;
import static digital_library.Search_book.copies;
import static digital_library.Search_book.date_of_issue;
import static digital_library.Search_book.search_tf;
import static digital_library.Search_book.searchbook;
import javax.swing.JOptionPane;

/**
 *
 * @author Rashda Khanzada
 */
public class Assign_to extends javax.swing.JFrame {

    /**
     * Creates new form Assign_to
     */
    public Assign_to() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        issue_date = new javax.swing.JTextField();
        name_tf = new javax.swing.JTextField();
        rollno_tf = new javax.swing.JTextField();
        dept_tf = new javax.swing.JTextField();
        book_assign = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        phone_tf = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"Assign book\"");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("issue date");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 280, 120, 40);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 40, 100, 40);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setText("Roll no");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 100, 100, 40);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("Department");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 160, 120, 40);
        getContentPane().add(issue_date);
        issue_date.setBounds(250, 290, 160, 30);
        getContentPane().add(name_tf);
        name_tf.setBounds(250, 40, 160, 30);
        getContentPane().add(rollno_tf);
        rollno_tf.setBounds(250, 110, 160, 30);
        getContentPane().add(dept_tf);
        dept_tf.setBounds(250, 170, 160, 30);

        book_assign.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        book_assign.setText("Assign");
        book_assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_assignActionPerformed(evt);
            }
        });
        getContentPane().add(book_assign);
        book_assign.setBounds(170, 370, 110, 40);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setText("Phone num");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 220, 120, 40);
        getContentPane().add(phone_tf);
        phone_tf.setBounds(250, 230, 160, 30);

        setSize(new java.awt.Dimension(494, 480));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
  static int copies_left;
    private void book_assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_assignActionPerformed
     if(search_tf.getText().equals("CRJ 80342482")){   
         copies_left=--copies;
     }   
     if(search_tf.getText().equals("ICS 73812382")){   
         copies_left=--copies;
       
     }  
      if(search_tf.getText().equals("PIO 92381096")){   
         copies_left=--copies;
       
     }
       if(search_tf.getText().equals("BMS 92105696")){   
         copies_left=--copies;
       
     }
       
       if(search_tf.getText().equals("DSA 93217982")){   
         copies_left=--copies;
       
     }
       if(search_tf.getText().equals( "DSP 93217982")){   
         copies_left=--copies;
       
     }
         if(search_tf.getText().equals( "CDC 97357982")){   
         copies_left=--copies;
       
     }
      
        JOptionPane.showMessageDialog(null, "book assigned");
        Search_book s=new Search_book();
        this.hide();
        s.show();
        //date of issue
        String a=issue_date.getText();
        date_of_issue.setText(a);
        //available copies 
        available_copies.setText(String.valueOf(copies_left));
        searchbook();    
    }//GEN-LAST:event_book_assignActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Assign_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Assign_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Assign_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Assign_to.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Assign_to().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton book_assign;
    public static javax.swing.JTextField dept_tf;
    public static javax.swing.JTextField issue_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField name_tf;
    public static javax.swing.JTextField phone_tf;
    public static javax.swing.JTextField rollno_tf;
    // End of variables declaration//GEN-END:variables
}
