/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package digital_library;

import static digital_library.Assign_to.dept_tf;
import static digital_library.Assign_to.name_tf;
import static digital_library.Assign_to.phone_tf;
import static digital_library.Assign_to.rollno_tf;

import static digital_library.Student_Profile.dept_lb;
import static digital_library.Student_Profile.name_lb;
import static digital_library.Student_Profile.phone_lb;
import static digital_library.Student_Profile.roll_no_lb;
import javax.swing.JOptionPane;

/**
 *
 * @author Rashda Khanzada
 */
public class Search_book extends javax.swing.JFrame {

    /**
     * Creates new form Search_book
     */
    public Search_book() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_button = new javax.swing.JButton();
        search_tf = new javax.swing.JTextField();
        available_copies = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        assign_to = new javax.swing.JButton();
        assign_to_whom = new javax.swing.JButton();
        title_lb = new javax.swing.JLabel();
        no_of_copies = new javax.swing.JLabel();
        date_of_issue = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchimage.png"))); // NOI18N
        search_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(search_button);
        search_button.setBounds(350, 30, 60, 50);
        getContentPane().add(search_tf);
        search_tf.setBounds(80, 30, 270, 50);

        available_copies.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(available_copies);
        available_copies.setBounds(310, 300, 100, 40);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("date of issue");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 250, 180, 40);

        assign_to.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        assign_to.setText("Available copies");
        assign_to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assign_toActionPerformed(evt);
            }
        });
        getContentPane().add(assign_to);
        assign_to.setBounds(80, 300, 220, 41);

        assign_to_whom.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        assign_to_whom.setText("Assigned to whom");
        assign_to_whom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assign_to_whomActionPerformed(evt);
            }
        });
        getContentPane().add(assign_to_whom);
        assign_to_whom.setBounds(80, 200, 220, 41);

        title_lb.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(title_lb);
        title_lb.setBounds(190, 100, 290, 40);

        no_of_copies.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(no_of_copies);
        no_of_copies.setBounds(200, 150, 160, 40);

        date_of_issue.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(date_of_issue);
        date_of_issue.setBounds(240, 250, 160, 40);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setText("No of copies");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(80, 150, 120, 40);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel6.setText("Book Title");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 100, 110, 40);

        setSize(new java.awt.Dimension(507, 451));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //to whom the book is assigned 
    private void assign_to_whomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assign_to_whomActionPerformed
      
       Student_Profile s = new Student_Profile();
       this.hide();
       s.show();
       if(a.equals("CRJ 80342482")){
           name_lb.setText(name_tf.getText());
           roll_no_lb.setText(rollno_tf.getText());
           dept_lb.setText(dept_tf.getText());
           phone_lb.setText(phone_tf.getText());   
       }
       if(a.equals("ICS 73812382")){
           name_lb.setText(name_tf.getText());
           roll_no_lb.setText(rollno_tf.getText());
           dept_lb.setText(dept_tf.getText());
           phone_lb.setText(phone_tf.getText());   
       }
       if(a.equals("PIO 92381096")){
           name_lb.setText(name_tf.getText());
           roll_no_lb.setText(rollno_tf.getText());
           dept_lb.setText(dept_tf.getText());
           phone_lb.setText(phone_tf.getText());   
       }
       if(a.equals("BMS 92105696")){    
           name_lb.setText(name_tf.getText());
           roll_no_lb.setText(rollno_tf.getText());
           dept_lb.setText(dept_tf.getText());
           phone_lb.setText(phone_tf.getText());   
       }
       if(a.equals("DSA 93217982")){    
           name_lb.setText(name_tf.getText());
           roll_no_lb.setText(rollno_tf.getText());
           dept_lb.setText(dept_tf.getText());
           phone_lb.setText(phone_tf.getText());   
       }
       if(a.equals("DSP 93217982")){    
           name_lb.setText(name_tf.getText());
           roll_no_lb.setText(rollno_tf.getText());
           dept_lb.setText(dept_tf.getText());
           phone_lb.setText(phone_tf.getText());   
       }
       if(a.equals("CDC 97357982")){    
           name_lb.setText(name_tf.getText());
           roll_no_lb.setText(rollno_tf.getText());
           dept_lb.setText(dept_tf.getText());
           phone_lb.setText(phone_tf.getText());   
       }
       
    }//GEN-LAST:event_assign_to_whomActionPerformed
    
    
    private void assign_toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assign_toActionPerformed
    
       if(copies>1){
          Assign_to as=new Assign_to();
          this.hide();
          as.show();     
       }
      else 
         JOptionPane.showMessageDialog(null,"book can't be assigned");
        
    }//GEN-LAST:event_assign_toActionPerformed
    
    static String a;
    
    private void search_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_buttonActionPerformed
      a=search_tf.getText();
      if(a!=null){
         searchbook();      
      }
      else
          JOptionPane.showMessageDialog(null, "book not found");
    }//GEN-LAST:event_search_buttonActionPerformed
  static int copies;

   public static void searchbook(){
    if(a.equals("CRJ 80342482")){
       title_lb.setText("The Complete Reference Java");
       copies=8;
          
       }
    if(a.equals("ICS 73812382")){
       title_lb.setText("Introduction to Computer Science");
       copies=3;

    }
    if(a.equals("PIO 92381096")){
       title_lb.setText("Programming in Objective-C");
       copies=4;

    }
    if(a.equals("BMS 92105696")){
       title_lb.setText("Building Micro-Services");
       copies=4;

    }
    if(a.equals("DSA 93217982")){
       title_lb.setText("Data Structures and Algorithm");
       copies=4;

    }
    if(a.equals("DSP 93217982")){
       title_lb.setText("Design Pattern");
       copies=6;

    }
    if(a.equals("CDC 97357982")){
       title_lb.setText("Code Complete");
       copies=6;

    }
    no_of_copies.setText(String.valueOf(copies));  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_book.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_book().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assign_to;
    private javax.swing.JButton assign_to_whom;
    public static javax.swing.JLabel available_copies;
    public static javax.swing.JLabel date_of_issue;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel no_of_copies;
    private javax.swing.JButton search_button;
    public static javax.swing.JTextField search_tf;
    public static javax.swing.JLabel title_lb;
    // End of variables declaration//GEN-END:variables
}
