/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online_registration_form;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Rashda Khanzada
 */
public class OnlineForm extends javax.swing.JFrame {

    /**
     * Creates new form OnlineForm
     */
   Connection conn;
   PreparedStatement param;
   ResultSet rs;
    
    public OnlineForm() {
        initComponents();
        conn=ConnectionDB.ConnectDb();
                update();
    }
    String sql;
    public void update(){
      try{
         sql="select * from online_form order by id asc";
         param=conn.prepareStatement(sql);
         rs=param.executeQuery();  
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
       }
      finally{
         try{
             rs.close();
             param.close();     
         }
         catch(Exception e){}
      }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cnic_tf = new javax.swing.JTextField();
        name_tf = new javax.swing.JTextField();
        father_tf = new javax.swing.JTextField();
        phone_tf = new javax.swing.JTextField();
        attach_image = new javax.swing.JButton();
        image_lb = new javax.swing.JLabel();
        submit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Online Form");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("Gender");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 300, 150, 40);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 60, 90, 40);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setText("Father's Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 150, 40);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("Phone number");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 180, 150, 40);

        cnic_tf.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(cnic_tf);
        cnic_tf.setBounds(280, 240, 200, 40);

        name_tf.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(name_tf);
        name_tf.setBounds(280, 62, 200, 40);

        father_tf.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(father_tf);
        father_tf.setBounds(280, 120, 200, 40);

        phone_tf.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(phone_tf);
        phone_tf.setBounds(280, 180, 200, 40);

        attach_image.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        attach_image.setText("Attach Picture");
        attach_image.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attach_imageActionPerformed(evt);
            }
        });
        getContentPane().add(attach_image);
        attach_image.setBounds(530, 270, 180, 30);
        getContentPane().add(image_lb);
        image_lb.setBounds(530, 60, 180, 190);

        submit.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(320, 380, 120, 30);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setText("Cnic");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 240, 150, 40);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jRadioButton1.setText("Female");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(280, 330, 91, 41);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jRadioButton2.setText("Male");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(280, 300, 71, 41);

        setSize(new java.awt.Dimension(775, 483));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    File f; 
    ImageIcon icon;
    //Select the image
    private void attach_imageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attach_imageActionPerformed
        BufferedImage image = null;
        try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            f=choose.getSelectedFile();
            String filename=f.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image,image_lb.getWidth(),image_lb.getHeight()));
            image_lb.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
      
    }//GEN-LAST:event_attach_imageActionPerformed
    int id=0;
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
    String cnic=cnic_tf.getText();
            try{  
                 String sql="select id from online_form where cnic = ?";
                 param=conn.prepareStatement(sql);                
                 param.setString(1, cnic);            
                 rs=param.executeQuery();
                 
                 while(rs.next()){
                     System.out.println(rs.getInt(1));
                     id=rs.getInt(1);
                 }       
               //insert query
                 if(id==0){
                  
                         insert();
                         name_tf.setText("");
                         father_tf.setText("");
                         phone_tf.setText("");
                         cnic_tf.setText("");     
                         image_lb.setIcon(null);
                         DataTable data=new DataTable();
                         this.hide();
                         data.show();
                 
                 }
                   //update query
                 else{ 
                     updatequery();
                     DataTable data=new DataTable();
                     this.hide();
                     data.show();
                     
             
                 }
            }
            catch(Exception e){}
        
       
    }//GEN-LAST:event_submitActionPerformed
        private String gender;
    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        gender="Male";
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        gender="Female";
    }//GEN-LAST:event_jRadioButton1ActionPerformed
    //insert query
    public void insert(){
          try {
                            String a=name_tf.getText();
                            String b=father_tf.getText();
                            String c=phone_tf.getText();   
                            String d=cnic_tf.getText();

                            FileInputStream fin = null;
                            fin = new FileInputStream(f); //selected person image
                            int ln=(int) f.length();

                           sql="INSERT INTO online_form VALUES (?,?,?,?,?,?,?)";

                           param=conn.prepareStatement(sql);
                           param.setInt(1, 0);
                           param.setString(2,a);
                           param.setString(3,b);
                           param.setString(4,c);
                           param.setString(5,d);
                           param.setBinaryStream(6, fin, ln);//set the image first the image is converted into bytes then stored in BLOB
                           param.setString(7, gender);
                           int  i=param.executeUpdate();
                           if(i>0){
                               JOptionPane.showMessageDialog(null,"Data is inserted");
                            }
                           else
                               JOptionPane.showMessageDialog(null,"Data is not inserted");
                        } catch (FileNotFoundException ex) {
                            Logger.getLogger(OnlineForm.class.getName()).log(Level.SEVERE, null, ex);
                        } catch (SQLException ex) {
                           Logger.getLogger(OnlineForm.class.getName()).log(Level.SEVERE, null, ex);
                       }
                      
    }
    //update query
    public void updatequery(){
              try {
                sql="update online_form Set name= ? , FATHER_NAME = ? , phone_no = ? , cnic = ? where id = ?";
                param=conn.prepareStatement(sql);
                param.setString(1, name_tf.getText());
                param.setString(2, father_tf.getText());
                param.setString(3, phone_tf.getText());
                param.setString(4, cnic_tf.getText());
                param.setInt(5 , id);
                System.out.println("updated");
                param.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(DataTable.class.getName()).log(Level.SEVERE, null, ex);
            }
    }
    //resize the image according to the label
    private Image fitimage(Image img , int w , int h){
         BufferedImage resizedimage = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
         Graphics2D g2 = resizedimage.createGraphics();
         g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
         g2.drawImage(img, 0, 0,w,h,null);
         g2.dispose();
         return resizedimage;
    }
    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OnlineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OnlineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OnlineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OnlineForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OnlineForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton attach_image;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTextField cnic_tf;
    public static javax.swing.JTextField father_tf;
    public static javax.swing.JLabel image_lb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JRadioButton jRadioButton1;
    public static javax.swing.JRadioButton jRadioButton2;
    public static javax.swing.JTextField name_tf;
    public static javax.swing.JTextField phone_tf;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
