/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trainticketreservation;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Rashda Khanzada
 */
public class Seat_Reservation extends javax.swing.JFrame {
Connection conn;
   PreparedStatement param;
   ResultSet rs;
    public Seat_Reservation() {
        initComponents();
        conn=ConnectionDB.ConnectDb();
                update();
        combo1();
        combo2();
        combo3();
    }
    
    public void update(){
      try{
         String sql="select * from Train_Seats_Reserved order by id asc";
         param=conn.prepareStatement(sql);
         rs=param.executeQuery();  
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
       }
      finally{
         try{
             rs.close();
             param.close();     
         }
         catch(Exception e){}
      }
     }
    public void combo1(){
    String arr[]={"Allama Iqbal Express","Badar Express","Ghauri Express","Karakoram Express ","Shalimar Express","Tezgam"};
    
        for(int i=0;i<arr.length;i++){
          
            train_name.addItem(arr[i]);
  
         }
    }
    
    public void combo2(){
    String arr[]={"13:15","19:15","09:45","15:30","06:00","16:45"};
    
        for(int i=0;i<arr.length;i++){
          
            train_timing.addItem(arr[i]);
  
         }
    }
    
    public void combo3(){
    String arr[]={"800","700","1200","1500","2500","2000"};
    
        for(int i=0;i<arr.length;i++){
          
            ticket_price.addItem(arr[i]);
  
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        total_amount = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ticket_price = new javax.swing.JComboBox<>();
        train_name = new javax.swing.JComboBox<>();
        train_timing = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        num_of_seats = new javax.swing.JTextField();
        ok_button = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cancel_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        total_amount.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(total_amount);
        total_amount.setBounds(340, 320, 220, 40);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Train Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 50, 150, 40);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setText("Timing");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 120, 120, 40);

        ticket_price.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(ticket_price);
        ticket_price.setBounds(340, 190, 220, 40);

        train_name.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(train_name);
        train_name.setBounds(340, 50, 220, 40);

        train_timing.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(train_timing);
        train_timing.setBounds(340, 120, 220, 40);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("Ticket Price");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 190, 130, 40);

        num_of_seats.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(num_of_seats);
        num_of_seats.setBounds(340, 260, 220, 40);

        ok_button.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        ok_button.setText("OK");
        ok_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(ok_button);
        ok_button.setBounds(140, 420, 140, 50);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setText("No of Seats");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 260, 130, 40);

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel6.setText("Total Amount");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 330, 130, 40);

        cancel_button.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        cancel_button.setText("Cancel");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(cancel_button);
        cancel_button.setBounds(350, 420, 170, 50);

        setSize(new java.awt.Dimension(655, 542));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
String name_of_train;
    private void ok_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_buttonActionPerformed
        
          long ticketprice = Long.parseLong((String) ticket_price.getSelectedItem()); 
          int seats=Integer.parseInt(num_of_seats.getText());
          int amount=(int) (ticketprice*seats);
          total_amount.setText(String.valueOf(amount));
          JOptionPane.showMessageDialog(null, "Your seats are reserved");
          
          name_of_train= (String) train_name.getSelectedItem();
          String timing_of_train= (String) train_timing.getSelectedItem();
          String price_of_ticket= (String) ticket_price.getSelectedItem();
          
          try{
          String sql="INSERT INTO Train_Seats_Reserved VALUES (?,?,?,?,?,?)";

           param=conn.prepareStatement(sql);
           param.setInt(1, 0);
           param.setString(2,name_of_train);
           param.setString(3,timing_of_train);
           param.setString(4,price_of_ticket);
           param.setInt(5, seats);
           param.setInt(6,  amount);
 
           int  i=param.executeUpdate();
           if(i>0){
               JOptionPane.showMessageDialog(null,"Data is inserted");
            }
           else
               JOptionPane.showMessageDialog(null,"Data is not inserted");
 
      }
      catch(Exception e){
           System.out.println(e);
       }
          
    }//GEN-LAST:event_ok_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
      
         try{
          String sql="Delete from Train_Seats_Reserved where train_name=? ";
          param=conn.prepareStatement(sql);
                    param.setString(1 ,name_of_train);
                    int  i=param.executeUpdate();
                    if(i>0){
                        JOptionPane.showMessageDialog(null,"Data is deleted");
                        total_amount.setText("");
                        num_of_seats.setText("");
                    }
                    else
                        JOptionPane.showMessageDialog(null,"Data is  not deleted");
                }
         
         catch (SQLException w) {
                    JOptionPane.showMessageDialog(this, w);
                } 
    }//GEN-LAST:event_cancel_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Seat_Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Seat_Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Seat_Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Seat_Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Seat_Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField num_of_seats;
    private javax.swing.JButton ok_button;
    private javax.swing.JComboBox<String> ticket_price;
    private javax.swing.JLabel total_amount;
    private javax.swing.JComboBox<String> train_name;
    private javax.swing.JComboBox<String> train_timing;
    // End of variables declaration//GEN-END:variables
}
