/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package shoppinghub;

/**
 *
 * @author Rashda Khanzada
 */
public class Categories extends javax.swing.JFrame {

    /**
     * Creates new form Categories
     */
    public Categories() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mobiles_button = new javax.swing.JButton();
        electronics_button = new javax.swing.JButton();
        vehicles_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"Categories\"");
        setResizable(false);
        getContentPane().setLayout(null);

        mobiles_button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mobiles_button.setText("Mobiles");
        mobiles_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobiles_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(mobiles_button);
        mobiles_button.setBounds(100, 220, 220, 40);

        electronics_button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        electronics_button.setText("Electronics");
        electronics_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electronics_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(electronics_button);
        electronics_button.setBounds(100, 60, 220, 40);

        vehicles_button.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        vehicles_button.setText("Vehicles");
        vehicles_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicles_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(vehicles_button);
        vehicles_button.setBounds(100, 140, 220, 40);

        setSize(new java.awt.Dimension(453, 447));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void electronics_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electronics_buttonActionPerformed
        electronics_items e= new  electronics_items();
        this.hide();
        e.show();
    }//GEN-LAST:event_electronics_buttonActionPerformed

    private void vehicles_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicles_buttonActionPerformed
      vehicles v=new vehicles();
      this.hide();
      v.show();
    }//GEN-LAST:event_vehicles_buttonActionPerformed

    private void mobiles_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobiles_buttonActionPerformed
       mobiles m=new mobiles();
       this.hide();
       m.show();
    }//GEN-LAST:event_mobiles_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton electronics_button;
    private javax.swing.JButton mobiles_button;
    private javax.swing.JButton vehicles_button;
    // End of variables declaration//GEN-END:variables
}
