package trafficcrimemanagement;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class carowner extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement param;
    ResultSet rs;
    public carowner() {
        initComponents();
        conn=ConnectionDB.ConnectDb();    
                update();
    }
    public void update(){
        try{
           String sql="select * from carowner";
           param=conn.prepareStatement(sql);
           rs=param.executeQuery();
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally{
          try{
             rs.close();
             param.close();   
          }
          catch(Exception e){}}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        address_tf = new javax.swing.JTextField();
        searchbar_tf = new javax.swing.JTextField();
        name_tf = new javax.swing.JTextField();
        model_tf = new javax.swing.JTextField();
        cnic_tf = new javax.swing.JTextField();
        searchbar_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        car_image = new javax.swing.JLabel();
        person_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"Owner Details \"");
        setResizable(false);
        getContentPane().setLayout(null);

        address_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(address_tf);
        address_tf.setBounds(210, 300, 230, 40);

        searchbar_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        searchbar_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbar_tfActionPerformed(evt);
            }
        });
        searchbar_tf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchbar_tfKeyPressed(evt);
            }
        });
        getContentPane().add(searchbar_tf);
        searchbar_tf.setBounds(69, 30, 310, 50);

        name_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(name_tf);
        name_tf.setBounds(210, 120, 230, 40);

        model_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(model_tf);
        model_tf.setBounds(210, 180, 230, 40);

        cnic_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(cnic_tf);
        cnic_tf.setBounds(210, 240, 230, 40);

        searchbar_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchimage.png"))); // NOI18N
        searchbar_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbar_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(searchbar_button);
        searchbar_button.setBounds(380, 30, 60, 50);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Address");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 300, 100, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 120, 100, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Car Model");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 180, 100, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Cnic");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 240, 100, 40);
        getContentPane().add(car_image);
        car_image.setBounds(60, 380, 190, 190);
        getContentPane().add(person_image);
        person_image.setBounds(280, 380, 190, 190);

        setSize(new java.awt.Dimension(534, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void searchbar_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbar_buttonActionPerformed
         String a=searchbar_tf.getText();
         if(checkuser(a)){
            retrievedata();      
         }
         else
            JOptionPane.showMessageDialog(null,"number plate not found");
    }//GEN-LAST:event_searchbar_buttonActionPerformed

    private void searchbar_tfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchbar_tfKeyPressed
               String a=searchbar_tf.getText();
               int obj=evt.getKeyCode();
               if(obj==KeyEvent.VK_ENTER){
                  if(checkuser(a)){
                      retrievedata();
                  }
                  else
                     JOptionPane.showMessageDialog(null,"number plate not found");
              }
    }//GEN-LAST:event_searchbar_tfKeyPressed

    private void searchbar_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbar_tfActionPerformed
        
    }//GEN-LAST:event_searchbar_tfActionPerformed
 
    private void retrievedata(){
    try {
       
                String sql="Select * from carowner";
                rs=param.executeQuery();
                if(rs.next()){  
                     //retrieve the person detail
                        String name=rs.getString(1);
                        String carmodel=rs.getString(2);
                        String cnic=rs.getString(3);
                        String address=rs.getString(4);
                     //retrieve the car image from database and set to the label
                        byte[] img=rs.getBytes("CAR_IMAGE");
                        ImageIcon image=new ImageIcon(img);
                        Image im=image.getImage();
                        Image myimg=im.getScaledInstance(car_image.getWidth(),car_image.getHeight(),Image.SCALE_SMOOTH);
                        ImageIcon newimage=new ImageIcon(myimg);
                        car_image.setIcon(newimage);
                      //retrieve the person image from database and set to the label
                        byte[] per_img=rs.getBytes("PERSON_IMG");
                        ImageIcon per_image=new ImageIcon(per_img);
                        Image per_im=per_image.getImage();
                        Image perimg=per_im.getScaledInstance(car_image.getWidth(),car_image.getHeight(),Image.SCALE_SMOOTH);
                        ImageIcon personimage=new ImageIcon(perimg);
                        person_image.setIcon(personimage);
                      //display the person detail
                        name_tf.setText(name);
                        model_tf.setText(carmodel);
                        cnic_tf.setText(cnic);
                        address_tf.setText(address);
                       //car_image.setIcon(icon);
                  
                } } catch (SQLException ex) {
                Logger.getLogger(carowner.class.getName()).log(Level.SEVERE, null, ex);
            } 
 
    }
    //check the car's numberplate existence in database
    public boolean checkuser(String numplate){
          boolean user=false;   
          try {
                String sql="Select * from carowner where numberplate=?";
                param=conn.prepareStatement(sql);
                param.setString(1, numplate);
           
                rs=param.executeQuery();
                if(rs.next()){
                   user=true;      
                }
          } catch (SQLException ex) {
             Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
          }
          return user;
 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(carowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(carowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(carowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(carowner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new carowner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_tf;
    private javax.swing.JLabel car_image;
    private javax.swing.JTextField cnic_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField model_tf;
    private javax.swing.JTextField name_tf;
    private javax.swing.JLabel person_image;
    private javax.swing.JButton searchbar_button;
    private javax.swing.JTextField searchbar_tf;
    // End of variables declaration//GEN-END:variables
}
