package trafficcrimemanagement;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Rashda Khanzada
 */
public class ownerdetail extends javax.swing.JFrame {

    Connection conn;
   PreparedStatement param;
   ResultSet rs;
    public ownerdetail() {
        initComponents();
        conn=ConnectionDB.ConnectDb();
                update();
    }
    public void update(){
      try{
         String sql="select * from carowner";
         param=conn.prepareStatement(sql);
         rs=param.executeQuery();  
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
       }
      finally{
         try{
             rs.close();
             param.close();     
         }
         catch(Exception e){}
      }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        numplate_tf = new javax.swing.JTextField();
        name_tf = new javax.swing.JTextField();
        carmodel_tf = new javax.swing.JTextField();
        cnic_tf = new javax.swing.JTextField();
        address_tf = new javax.swing.JTextField();
        person_image_button = new javax.swing.JButton();
        person_image = new javax.swing.JLabel();
        car_image = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        car_image_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("number plate");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 300, 130, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 60, 70, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("car model");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 100, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("cnic");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 180, 100, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("address");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 240, 100, 40);

        numplate_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(numplate_tf);
        numplate_tf.setBounds(260, 300, 210, 40);

        name_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(name_tf);
        name_tf.setBounds(260, 60, 210, 40);

        carmodel_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(carmodel_tf);
        carmodel_tf.setBounds(260, 120, 210, 40);

        cnic_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(cnic_tf);
        cnic_tf.setBounds(260, 180, 210, 40);

        address_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(address_tf);
        address_tf.setBounds(260, 240, 210, 40);

        person_image_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        person_image_button.setText("Attach Picture");
        person_image_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                person_image_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(person_image_button);
        person_image_button.setBounds(920, 370, 170, 40);
        getContentPane().add(person_image);
        person_image.setBounds(870, 60, 260, 270);
        getContentPane().add(car_image);
        car_image.setBounds(550, 60, 260, 270);

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Insert");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 430, 170, 40);

        car_image_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        car_image_button.setText("Attach Car Image");
        car_image_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                car_image_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(car_image_button);
        car_image_button.setBounds(590, 370, 200, 40);

        setSize(new java.awt.Dimension(1287, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    File h; 
    private void person_image_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_person_image_buttonActionPerformed
             BufferedImage image = null;
        try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            h=choose.getSelectedFile();
            String filename=h.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image, person_image.getWidth(), person_image.getHeight()));
            person_image.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_person_image_buttonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          String a=name_tf.getText();
          String b=carmodel_tf.getText();
          String c=cnic_tf.getText();
          String d=address_tf.getText(); 
          String g=numplate_tf.getText();
          
          FileInputStream fin = null;
          FileInputStream gin = null;
          try {
           fin = new FileInputStream(f); //selected car file
           gin =new FileInputStream(h); //selected person file
          } catch (FileNotFoundException ex) {
           Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
          }
          
          int ln=(int) f.length();
          int lg=(int) h.length();
          try{
          String sql="INSERT INTO carowner VALUES (?,?,?,?,?,?,?)";

           param=conn.prepareStatement(sql);
           
           param.setString(1,a);
           param.setString(2,b);
           param.setString(3,c);
           param.setString(4,d);
           param.setString(5,g);
           param.setBinaryStream(6, fin, ln);//set the image first the image is converted into bytes then stored in BLOB
           param.setBinaryStream(7, gin, lg);//set the image first the image is converted into bytes then stored in BLOB
           int  i=param.executeUpdate();
           if(i>0){
               JOptionPane.showMessageDialog(null,"Data is inserted");
            }
           else
               JOptionPane.showMessageDialog(null,"Data is not inserted");
 
      }
          catch(Exception e){}
          name_tf.setText("");
          carmodel_tf.setText("");
          cnic_tf.setText("");
          address_tf.setText(""); 
          numplate_tf.setText("");
          car_image.setIcon(null);
          person_image.setIcon(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void car_image_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_car_image_buttonActionPerformed
        BufferedImage image = null;
        try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            f=choose.getSelectedFile();
            String filename=f.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image, car_image.getWidth(), car_image.getHeight()));
            car_image.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
     
    }//GEN-LAST:event_car_image_buttonActionPerformed

    File f; 
    ImageIcon icon;
     //resize the image according to the label
    private Image fitimage(Image img , int w , int h){
         BufferedImage resizedimage = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
         Graphics2D g2 = resizedimage.createGraphics();
         g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
         g2.drawImage(img, 0, 0,w,h,null);
         g2.dispose();
         return resizedimage;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ownerdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ownerdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ownerdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ownerdetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ownerdetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address_tf;
    private javax.swing.JLabel car_image;
    private javax.swing.JButton car_image_button;
    private javax.swing.JTextField carmodel_tf;
    private javax.swing.JTextField cnic_tf;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField name_tf;
    private javax.swing.JTextField numplate_tf;
    private javax.swing.JLabel person_image;
    private javax.swing.JButton person_image_button;
    // End of variables declaration//GEN-END:variables
}
