/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fee_management;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Rashda Khanzada
 */
public class Record_display extends javax.swing.JFrame {

    /**
     * Creates new form Record_display
     */
   Connection conn;
   PreparedStatement param;
   ResultSet rs;
   
    public Record_display() {
        initComponents();
        conn=ConnectionDB.ConnectDb();
                update();
    }
    
                       //****display all records****//
    public void update(){
      try{
         String sql="select * from fee_management order by id asc";
         param=conn.prepareStatement(sql);
         rs=param.executeQuery();
         table.setModel(DbUtils.resultSetToTableModel(rs));     
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
      }
      finally{
         try{
             rs.close();
             param.close();     
         }
         catch(Exception e){}
      }
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        monthcombo1 = new javax.swing.JComboBox<>();
        classcombo1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        display_record = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Records");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Month");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 60, 70, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Class");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 20, 70, 30);

        monthcombo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        monthcombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June ", "July", "August", "September", "October ", "November", "December" }));
        getContentPane().add(monthcombo1);
        monthcombo1.setBounds(180, 60, 210, 30);

        classcombo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        classcombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", " " }));
        getContentPane().add(classcombo1);
        classcombo1.setBounds(180, 20, 210, 30);

        table.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Name", "Father Name", "Date of Admission", "Last Fee Paid", "Monthly Fees", "Dues"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 110, 890, 340);

        display_record.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        display_record.setText("Display");
        display_record.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                display_recordActionPerformed(evt);
            }
        });
        getContentPane().add(display_record);
        display_record.setBounds(480, 30, 200, 50);

        setSize(new java.awt.Dimension(934, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

                //****filter and display the records according to the month and class****// 
    
    private void display_recordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_display_recordActionPerformed
       
        try {
           String classcombo=(String) classcombo1.getSelectedItem();
           String monthcombo=(String) monthcombo1.getSelectedItem();
           
           String sql="select * from fee_management where class=? and month=?";
           
           param=conn.prepareStatement(sql);
           param.setString(1,classcombo);
           param.setString(2,monthcombo);
           rs=param.executeQuery();
           table.setModel(DbUtils.resultSetToTableModel(rs));
           
       } catch (SQLException ex) {
           Logger.getLogger(Record_display.class.getName()).log(Level.SEVERE, null, ex);
       }
    }//GEN-LAST:event_display_recordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Record_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Record_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Record_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Record_display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Record_display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> classcombo1;
    private javax.swing.JButton display_record;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> monthcombo1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
