/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fee_management;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rashda Khanzada
 */
public class school_form extends javax.swing.JFrame {

    /**
     * Creates new form school_form
     */
   Connection conn;
   PreparedStatement param;
   ResultSet rs;
   
    public school_form() {
        initComponents();
        conn=ConnectionDB.ConnectDb();
                update();
    }

      public void update(){
      try{
         String sql="select * from fee_management order by id asc";
         param=conn.prepareStatement(sql);
         rs=param.executeQuery();  
      }
      catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
       }
      finally{
         try{
             rs.close();
             param.close();     
         }
         catch(Exception e){}
      }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dues_tf = new javax.swing.JTextField();
        name_tf = new javax.swing.JTextField();
        fathername_tf = new javax.swing.JTextField();
        date_tf = new javax.swing.JTextField();
        lastfee_tf = new javax.swing.JTextField();
        monthlyfees_tf = new javax.swing.JTextField();
        add_record_button = new javax.swing.JButton();
        month_combo = new javax.swing.JComboBox<>();
        class_combo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"School form\"");
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Month");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 320, 90, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 100, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Father's Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 70, 140, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Date of Admission");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 110, 170, 40);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Last fee paid");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 150, 130, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Monthly fees");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 190, 130, 40);

        dues_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(dues_tf);
        dues_tf.setBounds(250, 230, 200, 30);

        name_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(name_tf);
        name_tf.setBounds(250, 30, 200, 30);

        fathername_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(fathername_tf);
        fathername_tf.setBounds(250, 70, 200, 30);

        date_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(date_tf);
        date_tf.setBounds(250, 110, 200, 30);

        lastfee_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(lastfee_tf);
        lastfee_tf.setBounds(250, 150, 200, 30);

        monthlyfees_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(monthlyfees_tf);
        monthlyfees_tf.setBounds(250, 190, 200, 30);

        add_record_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_record_button.setText("Add Record");
        add_record_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_record_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(add_record_button);
        add_record_button.setBounds(150, 380, 190, 40);

        month_combo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        month_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June ", "July", "August", "September", "October ", "November", "December", " " }));
        getContentPane().add(month_combo);
        month_combo.setBounds(250, 320, 200, 30);

        class_combo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        class_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        getContentPane().add(class_combo);
        class_combo.setBounds(250, 280, 200, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Dues");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 230, 90, 40);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Class");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 280, 90, 40);

        setSize(new java.awt.Dimension(512, 495));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
                     //***inserting record***//
    private void add_record_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_record_buttonActionPerformed
       try {
           String name=name_tf.getText();
           String father_name=fathername_tf.getText();
           
           SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
           String c=date_tf.getText();
           java.util.Date sal_date=format.parse(c);
           long ms=sal_date.getTime();
           java.sql.Date admision_date=new java.sql.Date(ms);
           
           String lst_fee=lastfee_tf.getText();
           int last_fee=Integer.parseInt(lst_fee);
           String month_fee=monthlyfees_tf.getText();
           int monthly_fee=Integer.parseInt(month_fee);
           String due=dues_tf.getText();
           int dues=Integer.parseInt(due);
           
           String class_item = (String) class_combo.getSelectedItem();
           String month_item = (String) month_combo.getSelectedItem();
           
           String sql="INSERT INTO fee_management VALUES (?,?,?,?,?,?,?,?,?)";

           param=conn.prepareStatement(sql);
           param.setInt(1, 0);
           param.setString(2,name);
           param.setString(3,father_name);
           param.setDate(4,admision_date);
           param.setInt(5,last_fee);
           param.setInt(6,monthly_fee);
           param.setInt(7, dues);
           param.setString(8,  class_item);
           param.setString(9,  month_item);
           
           int  i=param.executeUpdate();
           
           if(i>0){
               JOptionPane.showMessageDialog(null,"Data is inserted");
            }
           else
               JOptionPane.showMessageDialog(null,"Data is not inserted");
           
       } catch (ParseException ex) {
           Logger.getLogger(school_form.class.getName()).log(Level.SEVERE, null, ex);
       } catch (SQLException ex) {
           Logger.getLogger(school_form.class.getName()).log(Level.SEVERE, null, ex);
       }
       
       Record_display record=new Record_display();
       this.hide();
       record.show();
       
    }//GEN-LAST:event_add_record_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(school_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(school_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(school_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(school_form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new school_form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_record_button;
    private javax.swing.JComboBox<String> class_combo;
    private javax.swing.JTextField date_tf;
    private javax.swing.JTextField dues_tf;
    private javax.swing.JTextField fathername_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lastfee_tf;
    private javax.swing.JComboBox<String> month_combo;
    private javax.swing.JTextField monthlyfees_tf;
    private javax.swing.JTextField name_tf;
    // End of variables declaration//GEN-END:variables
}
