package city_information_system;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static city_information_system.City_information.combobox3;
import static city_information_system.City_information.combobox3;
import static city_information_system.City_information.combobox2;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Rashda Khanzada
 */
public class City_info extends javax.swing.JFrame {

    /**
     * Creates new form City_info
     */
    Connection conn;
    PreparedStatement param;
    ResultSet rs;
    public City_info() {
        initComponents();
         conn=ConnectionDB.ConnectDb();    
                update();
                retrievedata();
    }
     public void update(){
        try{
           String sql="select * from city_information ";
           param=conn.prepareStatement(sql);
           rs=param.executeQuery();
        }
        catch(Exception e){
          JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally{
          try{
             rs.close();
             param.close();   
          }
          catch(Exception e){}}
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        hotel1_lbimg1 = new javax.swing.JLabel();
        hotel1_name1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mall1_lbimg1 = new javax.swing.JLabel();
        mall1_name1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        airport1_lbimg1 = new javax.swing.JLabel();
        airport1_name1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        hospital1_lbimg1 = new javax.swing.JLabel();
        hospital1_name1 = new javax.swing.JLabel();
        park1_name1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        park1_lbimg1 = new javax.swing.JLabel();
        hotel2_lbimg2 = new javax.swing.JLabel();
        hotel2_name2 = new javax.swing.JLabel();
        mall2_lbimg2 = new javax.swing.JLabel();
        mall2_name2 = new javax.swing.JLabel();
        hospital2_lbimg2 = new javax.swing.JLabel();
        hospital2_name2 = new javax.swing.JLabel();
        park2_lbimg2 = new javax.swing.JLabel();
        park2_name2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("\"City Details\"");
        setResizable(false);
        getContentPane().setLayout(null);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(1200, 2000));

        jPanel1.setPreferredSize(new java.awt.Dimension(914, 1998));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setText("Hotels:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(61, 45, 151, 30);
        jPanel1.add(hotel1_lbimg1);
        hotel1_lbimg1.setBounds(60, 140, 170, 150);

        hotel1_name1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel1.add(hotel1_name1);
        hotel1_name1.setBounds(61, 90, 180, 30);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Shopping Malls:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(610, 30, 151, 30);
        jPanel1.add(mall1_lbimg1);
        mall1_lbimg1.setBounds(620, 130, 170, 150);

        mall1_name1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel1.add(mall1_name1);
        mall1_name1.setBounds(620, 90, 180, 30);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setText("Airports:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(430, 580, 151, 30);
        jPanel1.add(airport1_lbimg1);
        airport1_lbimg1.setBounds(430, 670, 170, 150);

        airport1_name1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel1.add(airport1_name1);
        airport1_name1.setBounds(430, 620, 350, 30);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel4.setText("Hospitals:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 320, 151, 30);
        jPanel1.add(hospital1_lbimg1);
        hospital1_lbimg1.setBounds(60, 400, 170, 150);

        hospital1_name1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel1.add(hospital1_name1);
        hospital1_name1.setBounds(60, 360, 180, 30);

        park1_name1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel1.add(park1_name1);
        park1_name1.setBounds(640, 360, 180, 30);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel5.setText("Parks:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(620, 300, 151, 30);
        jPanel1.add(park1_lbimg1);
        park1_lbimg1.setBounds(640, 400, 170, 150);
        jPanel1.add(hotel2_lbimg2);
        hotel2_lbimg2.setBounds(290, 130, 170, 150);

        hotel2_name2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel1.add(hotel2_name2);
        hotel2_name2.setBounds(290, 90, 200, 30);
        jPanel1.add(mall2_lbimg2);
        mall2_lbimg2.setBounds(850, 130, 170, 150);

        mall2_name2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel1.add(mall2_name2);
        mall2_name2.setBounds(830, 90, 180, 30);
        jPanel1.add(hospital2_lbimg2);
        hospital2_lbimg2.setBounds(290, 390, 170, 150);

        hospital2_name2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel1.add(hospital2_name2);
        hospital2_name2.setBounds(290, 350, 180, 30);
        jPanel1.add(park2_lbimg2);
        park2_lbimg2.setBounds(860, 400, 170, 150);

        park2_name2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jPanel1.add(park2_name2);
        park2_name2.setBounds(860, 360, 180, 30);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 1090, 910);

        setSize(new java.awt.Dimension(1105, 954));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     private void retrievedata(){
       try {
             String city=(String) combobox3.getSelectedItem();
             String country=(String) combobox2.getSelectedItem();
             String sql="Select * from city_information where cityname=? and countryname=?";
              param=conn.prepareStatement(sql);
              param.setString(1,city);
              param.setString(2,country);
             rs=param.executeQuery();
             if(rs.next()){ 
                 
                 //hotel1
                 
              String hotel_name1=rs.getString(3);
              hotel1_name1.setText(hotel_name1);
              //set hotel img
              byte[] hotel_1img=rs.getBytes("HOTEL_IMG1");
              ImageIcon hotel_1image=new ImageIcon(hotel_1img);
              Image hotel_1im=hotel_1image.getImage();
              Image hotel1_img=hotel_1im.getScaledInstance(hotel1_lbimg1.getWidth(),hotel1_lbimg1.getHeight(),Image.SCALE_SMOOTH);
              ImageIcon hotel1_newimage=new ImageIcon(hotel1_img);
              hotel1_lbimg1.setIcon(hotel1_newimage);
              
                //hotel2
              
              String hotel_name2=rs.getString(13);
              hotel2_name2.setText(hotel_name2);
              //set hotel img
              byte[] hotel_2img=rs.getBytes("HOTEL_IMG2");
              ImageIcon hotel_2image=new ImageIcon(hotel_2img);
              Image hotel_2im=hotel_2image.getImage();
              Image hotel2_img=hotel_2im.getScaledInstance(hotel2_lbimg2.getWidth(),hotel2_lbimg2.getHeight(),Image.SCALE_SMOOTH);
              ImageIcon hotel2_newimage=new ImageIcon(hotel2_img);
              hotel2_lbimg2.setIcon(hotel2_newimage);
              
                //mall1
              String mall_name1=rs.getString(5);
              mall1_name1.setText(mall_name1);
              
              byte[] mall_1img=rs.getBytes("SHOPPING_IMG1");
              ImageIcon mall_1image=new ImageIcon(mall_1img);
              Image mall_1im=mall_1image.getImage();
              Image mall1_img=mall_1im.getScaledInstance(mall1_lbimg1.getWidth(),mall1_lbimg1.getHeight(),Image.SCALE_SMOOTH);
              ImageIcon mall1_newimage=new ImageIcon(mall1_img);
              mall1_lbimg1.setIcon(mall1_newimage);
              
              //mall2
              String mall_name2=rs.getString(15);
              mall2_name2.setText(mall_name2);
              
              byte[] mall_2img=rs.getBytes("SHOPPING_IMG2");
              ImageIcon mall_2image=new ImageIcon(mall_2img);
              Image mall_2im=mall_2image.getImage();
              Image mall2_img=mall_2im.getScaledInstance(mall2_lbimg2.getWidth(),mall2_lbimg2.getHeight(),Image.SCALE_SMOOTH);
              ImageIcon mall2_newimage=new ImageIcon(mall2_img);
              mall2_lbimg2.setIcon(mall2_newimage);
              
              //airport 
              
              String airport_name1=rs.getString(7);
              airport1_name1.setText(airport_name1);
              
              byte[] airport_1img=rs.getBytes("AIRPORT_IMG1");
              ImageIcon airport_1image=new ImageIcon(airport_1img);
              Image airport_1im=airport_1image.getImage();
              Image airport1_img=airport_1im.getScaledInstance(airport1_lbimg1.getWidth(),airport1_lbimg1.getHeight(),Image.SCALE_SMOOTH);
              ImageIcon airport1_newimage=new ImageIcon(airport1_img);
              airport1_lbimg1.setIcon(airport1_newimage);
              
              //hospital1
              
              String hospital_name1=rs.getString(9);
              hospital1_name1.setText(hospital_name1);
              
              byte[] hospital_1img=rs.getBytes("HOSPITAL_IMG1");
              ImageIcon hospital_1image=new ImageIcon(hospital_1img);
              Image hospital_1im=hospital_1image.getImage();
              Image hospital1_img=hospital_1im.getScaledInstance(hospital1_lbimg1.getWidth(),hospital1_lbimg1.getHeight(),Image.SCALE_SMOOTH);
              ImageIcon hospital1_newimage=new ImageIcon(hospital1_img);
              hospital1_lbimg1.setIcon(hospital1_newimage);
              
              //hospital2
              
              String hospital_name2=rs.getString(17);
              hospital2_name2.setText(hospital_name2);
              
              byte[] hospital_2img=rs.getBytes("HOSPITAL_IMG2");
              ImageIcon hospital_2image=new ImageIcon(hospital_2img);
              Image hospital_2im=hospital_2image.getImage();
              Image hospital2_img=hospital_2im.getScaledInstance(hospital2_lbimg2.getWidth(),hospital2_lbimg2.getHeight(),Image.SCALE_SMOOTH);
              ImageIcon hospital2_newimage=new ImageIcon(hospital2_img);
              hospital2_lbimg2.setIcon(hospital2_newimage);
              
              //park 1
              
              String park_name1=rs.getString(11);
              park1_name1.setText(park_name1);
              
              byte[] park_1img=rs.getBytes("PARK_IMG1");
              ImageIcon park_1image=new ImageIcon(park_1img);
              Image park_1im=park_1image.getImage();
              Image park1_img=hospital_1im.getScaledInstance(park1_lbimg1.getWidth(),park1_lbimg1.getHeight(),Image.SCALE_SMOOTH);
              ImageIcon park1_newimage=new ImageIcon(park1_img);
              park1_lbimg1.setIcon(park1_newimage);
              
               //park 2
              
              String park_name2=rs.getString(19);
              park2_name2.setText(park_name2);
              
              byte[] park_2img=rs.getBytes("PARK_IMG2");
              ImageIcon park_2image=new ImageIcon(park_2img);
              Image park_2im=park_2image.getImage();
              Image park2_img=hospital_1im.getScaledInstance(park2_lbimg2.getWidth(),park2_lbimg2.getHeight(),Image.SCALE_SMOOTH);
              ImageIcon park2_newimage=new ImageIcon(park2_img);
              park2_lbimg2.setIcon(park2_newimage);
              
             }
           
           
       } catch (SQLException ex) {
            Logger.getLogger(City_info.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(City_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(City_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(City_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(City_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new City_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airport1_lbimg1;
    private javax.swing.JLabel airport1_name1;
    private javax.swing.JLabel hospital1_lbimg1;
    private javax.swing.JLabel hospital1_name1;
    private javax.swing.JLabel hospital2_lbimg2;
    private javax.swing.JLabel hospital2_name2;
    private javax.swing.JLabel hotel1_lbimg1;
    private javax.swing.JLabel hotel1_name1;
    private javax.swing.JLabel hotel2_lbimg2;
    private javax.swing.JLabel hotel2_name2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mall1_lbimg1;
    private javax.swing.JLabel mall1_name1;
    private javax.swing.JLabel mall2_lbimg2;
    private javax.swing.JLabel mall2_name2;
    private javax.swing.JLabel park1_lbimg1;
    private javax.swing.JLabel park1_name1;
    private javax.swing.JLabel park2_lbimg2;
    private javax.swing.JLabel park2_name2;
    // End of variables declaration//GEN-END:variables
}
