/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package city_information_system;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Rashda Khanzada
 */
public class City_information extends javax.swing.JFrame {

    /**
     * Creates new form City_information
     */
    public City_information() {
        initComponents();
        combo1();
        combo2();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        combobox2 = new javax.swing.JComboBox<>();
        combobox3 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        combobox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel2.setText("Country :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 50, 130, 40);

        combobox2.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(combobox2);
        combobox2.setBounds(170, 140, 270, 40);

        combobox3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        combobox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hotels", "Hospitals", "Shopping Malls", "Parks", "Airports", " ", " " }));
        combobox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combobox3MouseClicked(evt);
            }
        });
        getContentPane().add(combobox3);
        combobox3.setBounds(110, 240, 270, 40);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel3.setText("City :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 140, 130, 40);

        combobox1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        getContentPane().add(combobox1);
        combobox1.setBounds(170, 50, 270, 40);

        setSize(new java.awt.Dimension(512, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void combobox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combobox3MouseClicked
       if(combobox3.getSelectedItem()!=null){
          /* City_info c=new City_info();
           this.hide();
           c.show();*/
          info i=new info();
          this.hide();
          i.show();
       }
    }//GEN-LAST:event_combobox3MouseClicked

    /**
     * @param args the command line arguments
     */
    
    //add countries in combo1
    public void combo1(){
    String arr[]={"Pakistan","Canada","Switzerland","United States"};
    
        for(int i=0;i<arr.length;i++){
          
            combobox1.addItem(arr[i]);
  
         }
    }
    //add cities in combo2
     public void combo2(){
    String arr[]={"Karachi","Tornoto","Geneva","New York"};
        for(int i=0;i<arr.length;i++){
            combobox2.addItem(arr[i]);           
  
         }
       
    }
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(City_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(City_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(City_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(City_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              City_information c=  new City_information();
              c.setVisible(true);
             
             
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> combobox1;
    public static javax.swing.JComboBox<String> combobox2;
    public static javax.swing.JComboBox<String> combobox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
