/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package city_information_system;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Rashda Khanzada
 */
public class Insert_city_information extends javax.swing.JFrame {

    /**
     * Creates new form Insert_city_information
     */
   Connection conn;
   PreparedStatement param;
   ResultSet rs;
    public Insert_city_information() {
        initComponents();
        conn=ConnectionDB.ConnectDb();
        update();
    }
    String sql;
    public void update(){
      try{
         sql="select * from city_information ";
         param=conn.prepareStatement(sql);
         rs=param.executeQuery();  
      }
      catch(Exception e){
          
       }
      finally{
         try{
             rs.close();
             param.close();     
         }
         catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
         }
      }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        city_tf = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        insert = new javax.swing.JButton();
        park1_img = new javax.swing.JButton();
        park1_lb = new javax.swing.JLabel();
        hospital1_img = new javax.swing.JButton();
        hospital1_lb = new javax.swing.JLabel();
        airport_img1 = new javax.swing.JButton();
        airport1_lb = new javax.swing.JLabel();
        hotel1_img = new javax.swing.JButton();
        hotel1_lb1 = new javax.swing.JLabel();
        hotel_tf = new javax.swing.JTextField();
        mall_img1 = new javax.swing.JButton();
        mall1_lb = new javax.swing.JLabel();
        hospital_tf = new javax.swing.JTextField();
        airport_tf = new javax.swing.JTextField();
        mall_tf = new javax.swing.JTextField();
        country_tf = new javax.swing.JTextField();
        park_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        hotel_tf1 = new javax.swing.JTextField();
        hotel2_lb2 = new javax.swing.JLabel();
        hotel2_img2 = new javax.swing.JButton();
        mall_tf1 = new javax.swing.JTextField();
        mall2_lb2 = new javax.swing.JLabel();
        mall2_img2 = new javax.swing.JButton();
        park_tf1 = new javax.swing.JTextField();
        park2_lb2 = new javax.swing.JLabel();
        park2_img2 = new javax.swing.JButton();
        hospital_tf1 = new javax.swing.JTextField();
        hospital2_lb2 = new javax.swing.JLabel();
        hospital2_img2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(2200, 2297));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(914, 2295));
        jPanel1.setLayout(null);
        jPanel1.add(city_tf);
        city_tf.setBounds(340, 20, 160, 30);

        jLabel7.setText("City name:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(260, 20, 70, 30);

        insert.setText("insert data");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        jPanel1.add(insert);
        insert.setBounds(350, 770, 120, 25);

        park1_img.setText("attach");
        park1_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park1_imgActionPerformed(evt);
            }
        });
        jPanel1.add(park1_img);
        park1_img.setBounds(630, 250, 67, 25);
        jPanel1.add(park1_lb);
        park1_lb.setBounds(590, 130, 130, 100);

        hospital1_img.setText("attach");
        hospital1_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospital1_imgActionPerformed(evt);
            }
        });
        jPanel1.add(hospital1_img);
        hospital1_img.setBounds(630, 480, 67, 25);
        jPanel1.add(hospital1_lb);
        hospital1_lb.setBounds(600, 370, 130, 100);

        airport_img1.setText("attach");
        airport_img1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airport_img1ActionPerformed(evt);
            }
        });
        jPanel1.add(airport_img1);
        airport_img1.setBounds(60, 720, 67, 25);
        jPanel1.add(airport1_lb);
        airport1_lb.setBounds(30, 600, 130, 100);

        hotel1_img.setText("attach");
        hotel1_img.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotel1_imgActionPerformed(evt);
            }
        });
        jPanel1.add(hotel1_img);
        hotel1_img.setBounds(50, 240, 67, 25);
        jPanel1.add(hotel1_lb1);
        hotel1_lb1.setBounds(20, 130, 130, 100);

        hotel_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotel_tfActionPerformed(evt);
            }
        });
        jPanel1.add(hotel_tf);
        hotel_tf.setBounds(20, 90, 150, 30);

        mall_img1.setText("attach");
        mall_img1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mall_img1ActionPerformed(evt);
            }
        });
        jPanel1.add(mall_img1);
        mall_img1.setBounds(60, 480, 67, 25);
        jPanel1.add(mall1_lb);
        mall1_lb.setBounds(30, 360, 130, 100);
        jPanel1.add(hospital_tf);
        hospital_tf.setBounds(590, 330, 150, 30);
        jPanel1.add(airport_tf);
        airport_tf.setBounds(20, 560, 150, 30);
        jPanel1.add(mall_tf);
        mall_tf.setBounds(20, 320, 150, 30);
        jPanel1.add(country_tf);
        country_tf.setBounds(110, 20, 140, 30);
        jPanel1.add(park_tf);
        park_tf.setBounds(580, 90, 150, 30);

        jLabel6.setText("Hospitals:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(590, 290, 150, 30);

        jLabel5.setText("Airports:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 520, 150, 30);

        jLabel4.setText("Shopping malls:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 280, 150, 30);

        jLabel3.setText("Hotels :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 60, 150, 30);

        jLabel2.setText("Country name:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 90, 30);

        jLabel1.setText("Parks:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(580, 60, 150, 30);

        hotel_tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotel_tf1ActionPerformed(evt);
            }
        });
        jPanel1.add(hotel_tf1);
        hotel_tf1.setBounds(190, 90, 150, 30);
        jPanel1.add(hotel2_lb2);
        hotel2_lb2.setBounds(190, 130, 130, 100);

        hotel2_img2.setText("attach");
        hotel2_img2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotel2_img2ActionPerformed(evt);
            }
        });
        jPanel1.add(hotel2_img2);
        hotel2_img2.setBounds(220, 240, 67, 25);
        jPanel1.add(mall_tf1);
        mall_tf1.setBounds(190, 320, 150, 30);
        jPanel1.add(mall2_lb2);
        mall2_lb2.setBounds(200, 360, 130, 100);

        mall2_img2.setText("attach");
        mall2_img2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mall2_img2ActionPerformed(evt);
            }
        });
        jPanel1.add(mall2_img2);
        mall2_img2.setBounds(230, 480, 67, 25);
        jPanel1.add(park_tf1);
        park_tf1.setBounds(750, 90, 150, 30);
        jPanel1.add(park2_lb2);
        park2_lb2.setBounds(760, 130, 130, 100);

        park2_img2.setText("attach");
        park2_img2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                park2_img2ActionPerformed(evt);
            }
        });
        jPanel1.add(park2_img2);
        park2_img2.setBounds(800, 250, 67, 25);
        jPanel1.add(hospital_tf1);
        hospital_tf1.setBounds(760, 330, 150, 30);
        jPanel1.add(hospital2_lb2);
        hospital2_lb2.setBounds(770, 370, 130, 100);

        hospital2_img2.setText("attach");
        hospital2_img2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospital2_img2ActionPerformed(evt);
            }
        });
        jPanel1.add(hospital2_img2);
        hospital2_img2.setBounds(800, 480, 67, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1010, 900);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(1247, 2297));
        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 880, 900);

        setSize(new java.awt.Dimension(1024, 946));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    File hotel1; 
    ImageIcon icon;
    BufferedImage image = null;
    private void hotel1_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotel1_imgActionPerformed

        try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            hotel1=choose.getSelectedFile();
            String filename=hotel1.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image,hotel1_lb1.getWidth(),hotel1_lb1.getHeight()));
            hotel1_lb1.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_hotel1_imgActionPerformed
   File mall1;
    private void mall_img1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mall_img1ActionPerformed
       try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            mall1=choose.getSelectedFile();
            String filename=mall1.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image,mall1_lb.getWidth(),mall1_lb.getHeight()));
            mall1_lb.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mall_img1ActionPerformed
   File airport1; 
    private void airport_img1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airport_img1ActionPerformed
        try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            airport1=choose.getSelectedFile();
            String filename=airport1.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image,airport1_lb.getWidth(),airport1_lb.getHeight()));
            airport1_lb.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_airport_img1ActionPerformed
    File hospital1;
    private void hospital1_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospital1_imgActionPerformed
         try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            hospital1=choose.getSelectedFile();
            String filename=hospital1.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image,hospital1_lb.getWidth(),hospital1_lb.getHeight()));
            hospital1_lb.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_hospital1_imgActionPerformed
  File park1;
    private void park1_imgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park1_imgActionPerformed
        try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            park1=choose.getSelectedFile();
            String filename=park1.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image,park1_lb.getWidth(),park1_lb.getHeight()));
            park1_lb.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_park1_imgActionPerformed

    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
            String country=country_tf.getText();
            String city=city_tf.getText();
            
            String hotel=hotel_tf.getText();
            String hotel1_1=hotel_tf1.getText();
            
            String mall= mall_tf.getText();
            String mall1_1= mall_tf1.getText();
            
            String airport=airport_tf.getText();
            
            String hospital=hospital_tf.getText();
            String hospital1_1=hospital_tf1.getText();
            
            String park=park_tf.getText();
            String park1_1=park_tf1.getText();
            
            FileInputStream hotel_1 = null;
            FileInputStream mall_1 = null;
            FileInputStream airport_1 = null;
            FileInputStream hospital_1 = null;
            FileInputStream park_1 = null;
            
            FileInputStream hotel_2 = null;
            FileInputStream mall_2 = null;
            FileInputStream hospital_2 = null;
            FileInputStream park_2 = null;
            try {
            hotel_1 = new FileInputStream(hotel1); 
            mall_1 = new FileInputStream(mall1); 
            airport_1 = new FileInputStream(airport1);
            hospital_1 = new FileInputStream(hospital1); 
            park_1 = new FileInputStream(park1); 
           
            hotel_2 = new FileInputStream(hotel2); 
            mall_2 = new FileInputStream(mall2); 
            hospital_2 = new FileInputStream(hospital2); 
            park_2 = new FileInputStream(park2);
          } catch (FileNotFoundException ex) { 
           Logger.getLogger(Insert_city_information.class.getName()).log(Level.SEVERE, null, ex);
       }
          
          int hotel_len=(int) hotel1.length();
          int mall_len=(int) mall1.length();
          int airport_len=(int) airport1.length();
          int hospital_len=(int) hospital1.length();
          int park_len=(int) park1.length();
          
          int hotel1_len=(int) hotel2.length();
          int mall1_len=(int) mall2.length();
          int hospital1_len=(int) hospital2.length();
          int park1_len=(int) park2.length();
          
          try{
           sql="INSERT INTO city_information VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

           param=conn.prepareStatement(sql);
           
           param.setString(1,country);
           param.setString(2,city);
           param.setString(3,hotel);
           param.setBinaryStream(4, hotel_1, hotel_len);
           param.setString(5,mall);
           param.setBinaryStream(6, mall_1, mall_len);
           param.setString(7,airport);
           param.setBinaryStream(8, airport_1, airport_len);
           param.setString(9,hospital);
           param.setBinaryStream(10, hospital_1, hospital_len);
           param.setString(11,park);
           param.setBinaryStream(12, park_1, park_len);
           param.setString(13, hotel1_1);
           param.setBinaryStream(14, hotel_2, hotel1_len);
           param.setString(15,mall1_1);
           param.setBinaryStream(16, mall_2, mall1_len);
           param.setString(17,hospital);
           param.setBinaryStream(18, hospital_2, hospital1_len);
           param.setString(19,park1_1);
           param.setBinaryStream(20, park_2, park1_len);
           int  i=param.executeUpdate();
           if(i>0){
               JOptionPane.showMessageDialog(null,"Data is inserted");
            }
           else
               JOptionPane.showMessageDialog(null,"Data is not inserted");
 
      }
          catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
          }
           country_tf.setText("");
           city_tf.setText("");
           hotel_tf.setText("");
           hotel_tf1.setText("");
           mall_tf.setText("");
           mall_tf1.setText("");
           airport_tf.setText("");
           hospital_tf.setText("");
           hospital_tf1.setText("");
           park_tf.setText("");
           park_tf1.setText("");
           hotel1_lb1.setIcon(null);
           hotel2_lb2.setIcon(null);
           mall1_lb.setIcon(null);
           mall2_lb2.setIcon(null);
           airport1_lb.setIcon(null);
           hospital1_lb.setIcon(null);
           hospital2_lb2.setIcon(null);
           park1_lb.setIcon(null);
           park2_lb2.setIcon(null);    
          
    }//GEN-LAST:event_insertActionPerformed

    private void hotel_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotel_tfActionPerformed
        
    }//GEN-LAST:event_hotel_tfActionPerformed

    private void hotel_tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotel_tf1ActionPerformed
       
    }//GEN-LAST:event_hotel_tf1ActionPerformed
    File hotel2;
    private void hotel2_img2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotel2_img2ActionPerformed
              
        try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            hotel2=choose.getSelectedFile();
            String filename=hotel2.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image,hotel2_lb2.getWidth(),hotel2_lb2.getHeight()));
            hotel2_lb2.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_hotel2_img2ActionPerformed
    File mall2;
    private void mall2_img2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mall2_img2ActionPerformed
       try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            mall2=choose.getSelectedFile();
            String filename=mall2.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image,mall2_lb2.getWidth(),mall2_lb2.getHeight()));
            mall2_lb2.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_mall2_img2ActionPerformed
     File park2;
    private void park2_img2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_park2_img2ActionPerformed
        try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            park2=choose.getSelectedFile();
            String filename=park2.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image,park2_lb2.getWidth(),park2_lb2.getHeight()));
            park2_lb2.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_park2_img2ActionPerformed
      File hospital2;
    private void hospital2_img2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospital2_img2ActionPerformed
         try{
            JFileChooser choose=new JFileChooser();
            choose.showOpenDialog(null);
            hospital2=choose.getSelectedFile();
            String filename=hospital2.getAbsolutePath();   
            image = ImageIO.read(new File(filename));
            icon=new ImageIcon(fitimage(image,hospital2_lb2.getWidth(),hospital2_lb2.getHeight()));
            hospital2_lb2.setIcon(icon);
        }
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_hospital2_img2ActionPerformed
   
    //resize the image according to the label
    private Image fitimage(Image img , int w , int h){
         BufferedImage resizedimage = new BufferedImage(w,h,BufferedImage.TYPE_INT_RGB);
         Graphics2D g2 = resizedimage.createGraphics();
         g2.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
         g2.drawImage(img, 0, 0,w,h,null);
         g2.dispose();
         return resizedimage;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_city_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_city_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_city_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_city_information.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_city_information().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airport1_lb;
    private javax.swing.JButton airport_img1;
    private javax.swing.JTextField airport_tf;
    private javax.swing.JTextField city_tf;
    private javax.swing.JTextField country_tf;
    private javax.swing.JButton hospital1_img;
    private javax.swing.JLabel hospital1_lb;
    private javax.swing.JButton hospital2_img2;
    private javax.swing.JLabel hospital2_lb2;
    private javax.swing.JTextField hospital_tf;
    private javax.swing.JTextField hospital_tf1;
    private javax.swing.JButton hotel1_img;
    private javax.swing.JLabel hotel1_lb1;
    private javax.swing.JButton hotel2_img2;
    private javax.swing.JLabel hotel2_lb2;
    private javax.swing.JTextField hotel_tf;
    private javax.swing.JTextField hotel_tf1;
    private javax.swing.JButton insert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mall1_lb;
    private javax.swing.JButton mall2_img2;
    private javax.swing.JLabel mall2_lb2;
    private javax.swing.JButton mall_img1;
    private javax.swing.JTextField mall_tf;
    private javax.swing.JTextField mall_tf1;
    private javax.swing.JButton park1_img;
    private javax.swing.JLabel park1_lb;
    private javax.swing.JButton park2_img2;
    private javax.swing.JLabel park2_lb2;
    private javax.swing.JTextField park_tf;
    private javax.swing.JTextField park_tf1;
    // End of variables declaration//GEN-END:variables
}
