/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my_travel_cost;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static my_travel_cost.Cost_of_Transfer.combobox1;
import static my_travel_cost.Cost_of_Transfer.combobox2;
import static my_travel_cost.Cost_of_Transfer.distance_lb;
import static my_travel_cost.Cost_of_Transfer.drivercharges_tf;
import static my_travel_cost.Cost_of_Transfer.dvrcharges_lb;
import static my_travel_cost.Cost_of_Transfer.item_lb;
import static my_travel_cost.Cost_of_Transfer.no_of_trks;
import static my_travel_cost.Cost_of_Transfer.petrolcost_lb;
import static my_travel_cost.Cost_of_Transfer.petrolcost_tf;
import static my_travel_cost.Cost_of_Transfer.totaldistance_tf;

/**
 *
 * @author Rashda Khanzada
 */
public class total_bill extends javax.swing.JFrame {

    /**
     * Creates new form total_bill
     */
   
    public total_bill() {
        initComponents();
        calculate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        cost_per_transfer = new javax.swing.JTextField();
        print_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Total Cost Per Transfer");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 40, 210, 30);

        cost_per_transfer.setEditable(false);
        cost_per_transfer.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(cost_per_transfer);
        cost_per_transfer.setBounds(320, 40, 200, 30);

        print_button.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        print_button.setText("Print");
        print_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(print_button);
        print_button.setBounds(400, 440, 130, 30);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 110, 460, 310);

        setSize(new java.awt.Dimension(593, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void print_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_print_buttonActionPerformed
         try {
            jTextArea1.print();
        } catch (PrinterException ex) {
            Logger.getLogger(total_bill.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_print_buttonActionPerformed
     //calculation of total billing
     public void calculate(){
        int no_of_trucks = Integer.parseInt((String)combobox1.getSelectedItem()); 
        Object itms=combobox2.getSelectedItem();
        int petrol_cost=Integer.parseInt(petrolcost_tf.getText());
        long distance=Long.parseLong(totaldistance_tf.getText());
        long dvr_charges=Long.parseLong(drivercharges_tf.getText());
        
        //total cost per transfer
        
        Long total_cost=(petrol_cost*distance)+dvr_charges;
        String tot_cost=String.valueOf(total_cost);
        cost_per_transfer.setText(tot_cost);
        
        //total bill 
        
        Long total_bill=(petrol_cost+dvr_charges)*no_of_trucks;
        String totl_bill=String.valueOf(total_bill);
       jTextArea1.setText("\tTOTAL BILL RECEIPT\n\n");
       jTextArea1.setText(jTextArea1.getText()+no_of_trks.getText()+"\t   :      "+no_of_trucks+"\n");
       jTextArea1.setText(jTextArea1.getText()+item_lb.getText()+"\t   :      "+itms+"\n");
       jTextArea1.setText(jTextArea1.getText()+petrolcost_lb.getText()+"   :     "+petrol_cost+"\n");
       jTextArea1.setText(jTextArea1.getText()+distance_lb.getText()+" : "+distance+"\n");
       jTextArea1.setText(jTextArea1.getText()+dvrcharges_lb.getText()+"\t   :      "+dvr_charges+"\n");
       jTextArea1.setText(jTextArea1.getText()+"total bill"+"\t   :      "+totl_bill+"\n\n");
       jTextArea1.setText(jTextArea1.getText()+"\tSignature:_______________________");      
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(total_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(total_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(total_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(total_bill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               total_bill b= new total_bill();
               b.setVisible(true);
            
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cost_per_transfer;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton print_button;
    // End of variables declaration//GEN-END:variables
}
